services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    restart: unless-stopped
